name: smart_pay
description: A unified Flutter payments toolkit. Configure gateways (Stripe now; more soon), render a single methods widget, and checkout via one API.
version: 0.0.1
repository: https://github.com/muhammadwaqasdev/smart_pay
issue_tracker: https://github.com/muhammadwaqasdev/smart_pay/issues
homepage: https://github.com/muhammadwaqasdev/smart_pay

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^11.5.0
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

